import localFont from "next/font/local";

import type { Metadata } from "next";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div style={{ display: "flex", flexDirection: "column" }}>
          <a href={"/Sample1"}>Sample1</a>
          <a href={"/Sample2"}>Sample2</a>
          <a href={"/Sample3"}>Sample3</a>
          <a href={"/Sample4"}>Sample4</a>
        </div>
        {children}
      </body>
    </html>
  );
}
